<h2 style="text-align:center;color:#0F4C81;">
PyTorch Code Module
</h2>

PyTorch is not the only library that deals with multidimensional arrays. NumPy is by far the most popular multidimensional array library. PyTorch features seamless interoperability with NumPy, which brings with it first-class integration with the rest of the scientific libraries in Python, such as SciPy, Scikit-learn and Pandas.

Compared to NumPy arrays, PyTorch tensors have a few superpowers, such as the ability to perform very fast operations on graphical processing units (GPUs), distribute operations on multiple devices or machines, and keep track of the graph of computations that created them. These are all important features when implementing a modern deep learning library.

### **1. Creating Tensors**

PyTorch provides various ways to create tensors, from manually specifying data to using built-in functions for initialization. Below are some common methods:


#### **1.1 Creating a Tensor from Data**
You can create a tensor manually by passing a Python list or NumPy array to `torch.tensor()`. 

In [1]:
import torch

# Creating a tensor from a list
tensor1 = torch.tensor([1, 2, 3, 4, 5])
print(tensor1)

# Creating a tensor with floating-point values
tensor2 = torch.tensor([1.0, 2.0, 3.0])
print(tensor2)

# Specifying a data type explicitly
tensor3 = torch.tensor([1, 2, 3], dtype=torch.float32)
print(tensor3)

tensor([1, 2, 3, 4, 5])
tensor([1., 2., 3.])
tensor([1., 2., 3.])


#### **1.2 Initializing Tensors**
You can create tensors with default values using different functions:

- `torch.zeros(size)`: Creates a tensor filled with zeros.
- `torch.ones(size)`: Creates a tensor filled with ones.
- `torch.rand(size)`: Creates a tensor with random values from a uniform distribution (`[0,1)`).
- `torch.randn(size)`: Creates a tensor with random values from a normal distribution (mean=0, std=1).

In [2]:
# Creating tensors with predefined values
zeros_tensor = torch.zeros(3, 3)  # 3x3 tensor filled with zeros
ones_tensor = torch.ones(2, 4)    # 2x4 tensor filled with ones
rand_tensor = torch.rand(2, 2)    # 2x2 tensor with random values in [0,1)
randn_tensor = torch.randn(3, 3)  # 3x3 tensor with normal distribution values

print("Zeros Tensor:\n", zeros_tensor)
print("Ones Tensor:\n", ones_tensor)
print("Random Tensor (Uniform):\n", rand_tensor)
print("Random Tensor (Normal):\n", randn_tensor)

Zeros Tensor:
 tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
Ones Tensor:
 tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.]])
Random Tensor (Uniform):
 tensor([[0.3867, 0.5878],
        [0.3218, 0.0407]])
Random Tensor (Normal):
 tensor([[-0.9435,  0.0516, -0.6080],
        [-0.0529, -0.1738,  0.5972],
        [-1.8542, -1.2465, -1.6267]])


#### **1.3 Creating Sequences**
You can create sequences using `torch.arange()` and `torch.linspace()`.

- `torch.arange(start, end, step)`: Creates a tensor with values in a specified range.
- `torch.linspace(start, end, steps)`: Creates a tensor with `steps` number of evenly spaced values.

In [3]:
# Creating a range of values with arange
range_tensor = torch.arange(0, 10, 2)  # [0, 2, 4, 6, 8]
print("Range Tensor:", range_tensor)

# Creating evenly spaced values with linspace
linspace_tensor = torch.linspace(0, 1, 5)  # [0.0, 0.25, 0.5, 0.75, 1.0]
print("Linspace Tensor:", linspace_tensor)

Range Tensor: tensor([0, 2, 4, 6, 8])
Linspace Tensor: tensor([0.0000, 0.2500, 0.5000, 0.7500, 1.0000])


#### **1.4 Special Tensors**
PyTorch provides functions for creating special tensors:

- `torch.eye(n)`: Creates an identity matrix of size `n × n`.
- `torch.full(size, value)`: Creates a tensor of a given shape, filled with a specified value.

In [4]:
# Creating an identity matrix
identity_tensor = torch.eye(4)  # 4x4 identity matrix
print("Identity Tensor:\n", identity_tensor)

# Creating a tensor filled with a constant value
full_tensor = torch.full((3, 3), 7)  # 3x3 tensor filled with 7s
print("Full Tensor:\n", full_tensor)

Identity Tensor:
 tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]])
Full Tensor:
 tensor([[7, 7, 7],
        [7, 7, 7],
        [7, 7, 7]])


---

## **2. Reshaping and Changing Dimensions**

Reshaping tensors is a crucial part of working with PyTorch. This section covers various operations to modify tensor dimensions while keeping data intact.

### **2.1 Squeeze & Unsqueeze**
- `torch.squeeze(tensor)`: Removes dimensions of size 1.
- `torch.unsqueeze(tensor, dim)`: Adds a new dimension.

In [5]:
import torch

# Creating a tensor with extra dimensions
tensor = torch.rand(1, 3, 1, 4)
print("Original Tensor Shape:", tensor.shape)

# Removing dimensions of size 1
squeezed_tensor = torch.squeeze(tensor)  # Removes all size-1 dimensions
print("Squeezed Tensor Shape:", squeezed_tensor.shape)

# Removing only a specific dimension
squeezed_tensor_dim2 = torch.squeeze(tensor, dim=2)
print("Squeezed Tensor (dim=2) Shape:", squeezed_tensor_dim2.shape)

# Adding a new dimension
unsqueezed_tensor = torch.unsqueeze(tensor, dim=0)
print("Unsqueezed Tensor Shape:", unsqueezed_tensor.shape)

Original Tensor Shape: torch.Size([1, 3, 1, 4])
Squeezed Tensor Shape: torch.Size([3, 4])
Squeezed Tensor (dim=2) Shape: torch.Size([1, 3, 4])
Unsqueezed Tensor Shape: torch.Size([1, 1, 3, 1, 4])


### **2.2 View & Reshape**
- `tensor.view(shape)`: Changes the shape without modifying data layout (requires contiguous memory).
- `tensor.reshape(shape)`: Similar to `view`, but can create a copy if necessary.

In [6]:
# Creating a 2D tensor
tensor = torch.arange(8)
print("Original Tensor:", tensor)

# Reshaping it to 2x4
reshaped_tensor = tensor.view(2, 4)
print("Reshaped Tensor (2x4):\n", reshaped_tensor)

# Reshaping using reshape() (safe for non-contiguous memory)
reshaped_tensor2 = tensor.reshape(4, 2)
print("Reshaped Tensor (4x2):\n", reshaped_tensor2)

Original Tensor: tensor([0, 1, 2, 3, 4, 5, 6, 7])
Reshaped Tensor (2x4):
 tensor([[0, 1, 2, 3],
        [4, 5, 6, 7]])
Reshaped Tensor (4x2):
 tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7]])


### **2.3 Transpose & Permute**
- `tensor.T`: Swaps the last two dimensions (shortcut for 2D matrices).
- `tensor.transpose(dim0, dim1)`: Swaps any two dimensions.
- `tensor.permute(*dims)`: Rearranges dimensions arbitrarily.

In [7]:
# Creating a 2D matrix
matrix = torch.rand(3, 4)
print("Original Matrix Shape:", matrix.shape)

# Transposing the matrix (shortcut for 2D)
transposed_matrix = matrix.T
print("Transposed Matrix Shape:", transposed_matrix.shape)

# Swapping two specific dimensions
tensor_3d = torch.rand(2, 3, 4)
transposed_tensor = tensor_3d.transpose(1, 2)
print("Transposed Tensor Shape:", transposed_tensor.shape)

# Permuting dimensions
permuted_tensor = tensor_3d.permute(2, 0, 1)
print("Permuted Tensor Shape:", permuted_tensor.shape)

Original Matrix Shape: torch.Size([3, 4])
Transposed Matrix Shape: torch.Size([4, 3])
Transposed Tensor Shape: torch.Size([2, 4, 3])
Permuted Tensor Shape: torch.Size([4, 2, 3])


### **2.4 Flatten & Expand**
- `tensor.flatten(start_dim, end_dim)`: Converts tensor to 1D (or partially flattens).
- `tensor.expand(new_shape)`: Expands dimensions without copying data.
- `tensor.repeat(repeats)`: Repeats data (creates a new memory allocation).

In [8]:
# Creating a multi-dimensional tensor
tensor_4d = torch.rand(2, 3, 4, 5)

# Flattening the tensor completely
flattened_tensor = tensor_4d.flatten()
print("Flattened Tensor Shape:", flattened_tensor.shape)

# Flattening only a specific range of dimensions
partially_flattened_tensor = tensor_4d.flatten(start_dim=1, end_dim=2)
print("Partially Flattened Tensor Shape:", partially_flattened_tensor.shape)

# Expanding a tensor (without copying data)
tensor_exp = torch.rand(1, 3)
expanded_tensor = tensor_exp.expand(5, 3)  # Expands along the first dimension
print("Expanded Tensor Shape:", expanded_tensor.shape)

# Repeating a tensor (allocates new memory)
repeated_tensor = tensor_exp.repeat(2, 1)
print("Repeated Tensor Shape:", repeated_tensor.shape)

Flattened Tensor Shape: torch.Size([120])
Partially Flattened Tensor Shape: torch.Size([2, 12, 5])
Expanded Tensor Shape: torch.Size([5, 3])
Repeated Tensor Shape: torch.Size([2, 3])


---

### **3. Indexing & Slicing**
- `tensor[idx]`: Basic indexing
- `tensor[start:end]`: Slicing
- `tensor[..., idx]`: Select last dimension
- `tensor.masked_select(mask)`: Select elements based on condition
- `tensor.index_select(dim, indices)`: Select elements along a specific dimension

---

## **3. Indexing & Slicing**

Indexing and slicing allow us to extract specific elements or sub-tensors from a PyTorch tensor.

### **3.1 Basic Indexing**
You can access elements in a tensor using standard Python indexing.

In [9]:
import torch

# Creating a tensor
tensor = torch.tensor([[10, 20, 30], [40, 50, 60], [70, 80, 90]])
print("Original Tensor:\n", tensor)

# Accessing a single element
print("Element at (0,1):", tensor[0, 1])  # Output: 20

# Accessing an entire row
print("First Row:", tensor[0])

# Accessing an entire column
print("First Column:", tensor[:, 0])

Original Tensor:
 tensor([[10, 20, 30],
        [40, 50, 60],
        [70, 80, 90]])
Element at (0,1): tensor(20)
First Row: tensor([10, 20, 30])
First Column: tensor([10, 40, 70])


### **3.2 Slicing**
Slicing allows selecting specific ranges from tensors.

In [10]:
# Selecting a sub-tensor
sub_tensor = tensor[0:2, 1:]  # Rows 0 to 1, columns 1 to end
print("Sub-Tensor:\n", sub_tensor)

# Using step in slicing
stepped_tensor = tensor[:, ::2]  # Select every second column
print("Tensor with Step:\n", stepped_tensor)

Sub-Tensor:
 tensor([[20, 30],
        [50, 60]])
Tensor with Step:
 tensor([[10, 30],
        [40, 60],
        [70, 90]])


### **3.3 Ellipsis (`...`) for Slicing**
Ellipsis (`...`) is useful for selecting elements in high-dimensional tensors.

In [11]:
# Creating a 3D tensor
tensor_3d = torch.rand(2, 3, 4)
print("3D Tensor Shape:", tensor_3d.shape)

# Using ellipsis to select the last dimension
print("Selected Last Dimension:\n", tensor_3d[..., -1])

3D Tensor Shape: torch.Size([2, 3, 4])
Selected Last Dimension:
 tensor([[0.7568, 0.9949, 0.0275],
        [0.9074, 0.6104, 0.9144]])


### **3.4 Masked Indexing**
Masked indexing allows selecting elements based on conditions.

In [12]:
# Creating a tensor
tensor = torch.tensor([5, 15, 25, 35, 45])

# Selecting elements greater than 20
mask = tensor > 20
selected_elements = tensor[mask]
print("Elements > 20:", selected_elements)

Elements > 20: tensor([25, 35, 45])


### **3.5 Index Select**
`torch.index_select()` selects elements along a specific dimension using an index tensor.

In [13]:
# Creating a tensor
tensor = torch.tensor([[10, 20, 30], [40, 50, 60], [70, 80, 90]])

# Selecting specific rows
indices = torch.tensor([0, 2])  # Selecting first and last row
selected_rows = torch.index_select(tensor, dim=0, index=indices)
print("Selected Rows:\n", selected_rows)

# Selecting specific columns
indices = torch.tensor([1, 2])  # Selecting second and third columns
selected_columns = torch.index_select(tensor, dim=1, index=indices)
print("Selected Columns:\n", selected_columns)

Selected Rows:
 tensor([[10, 20, 30],
        [70, 80, 90]])
Selected Columns:
 tensor([[20, 30],
        [50, 60],
        [80, 90]])


---

## **4. Combining Tensors**

PyTorch provides several ways to combine tensors, including concatenation, stacking, and tiling.

### **4.1 Concatenation**
- `torch.cat(tensors, dim)`: Concatenates tensors along a given dimension.

In [14]:
import torch

# Creating two tensors
tensor1 = torch.tensor([[1, 2], [3, 4]])
tensor2 = torch.tensor([[5, 6], [7, 8]])

# Concatenating along rows (dim=0)
concat_rows = torch.cat((tensor1, tensor2), dim=0)
print("Concatenated along Rows:\n", concat_rows)

# Concatenating along columns (dim=1)
concat_cols = torch.cat((tensor1, tensor2), dim=1)
print("Concatenated along Columns:\n", concat_cols)

Concatenated along Rows:
 tensor([[1, 2],
        [3, 4],
        [5, 6],
        [7, 8]])
Concatenated along Columns:
 tensor([[1, 2, 5, 6],
        [3, 4, 7, 8]])


### **4.2 Stacking**
- `torch.stack(tensors, dim)`: Creates a new dimension and stacks tensors along that dimension.

In [15]:
# Stacking along a new dimension
stacked_tensor = torch.stack((tensor1, tensor2), dim=0)
print("Stacked Tensor Shape:", stacked_tensor.shape)

Stacked Tensor Shape: torch.Size([2, 2, 2])


### **4.3 Repeat & Expand**
- `torch.repeat(repeats)`: Repeats a tensor along specified dimensions (allocates new memory).
- `torch.expand(new_shape)`: Expands a tensor without copying data.

In [16]:
# Creating a 1D tensor
tensor = torch.tensor([[1, 2]])

# Repeating along rows and columns
repeated_tensor = tensor.repeat(2, 3)
print("Repeated Tensor:\n", repeated_tensor)

# Expanding a tensor
expanded_tensor = tensor.expand(3, 2)  # Expands without copying
print("Expanded Tensor:\n", expanded_tensor)

Repeated Tensor:
 tensor([[1, 2, 1, 2, 1, 2],
        [1, 2, 1, 2, 1, 2]])
Expanded Tensor:
 tensor([[1, 2],
        [1, 2],
        [1, 2]])


### **4.4 Meshgrid for Combination**
- `torch.meshgrid(tensors)`: Generates coordinate grids from 1D tensors.

In [17]:
# Creating coordinate ranges
x = torch.tensor([1, 2, 3])
y = torch.tensor([4, 5])

# Generating a meshgrid
grid_x, grid_y = torch.meshgrid(x, y, indexing="ij")
print("Grid X:\n", grid_x)
print("Grid Y:\n", grid_y)

Grid X:
 tensor([[1, 1],
        [2, 2],
        [3, 3]])
Grid Y:
 tensor([[4, 5],
        [4, 5],
        [4, 5]])


---

## **5. Mathematical Operations on Tensors**

PyTorch supports various element-wise, matrix, and reduction operations.

### **5.1 Element-wise Operations**
These operations are performed on corresponding elements of tensors.

In [18]:
import torch

# Creating two tensors
a = torch.tensor([1.0, 2.0, 3.0])
b = torch.tensor([4.0, 5.0, 6.0])

# Basic arithmetic operations
print("Addition:", a + b)
print("Subtraction:", a - b)
print("Multiplication:", a * b)
print("Division:", a / b)
print("Exponentiation:", a ** 2)

Addition: tensor([5., 7., 9.])
Subtraction: tensor([-3., -3., -3.])
Multiplication: tensor([ 4., 10., 18.])
Division: tensor([0.2500, 0.4000, 0.5000])
Exponentiation: tensor([1., 4., 9.])


PyTorch also provides equivalent functions:
- `torch.add(a, b)`, `torch.sub(a, b)`, `torch.mul(a, b)`, `torch.div(a, b)`, `torch.pow(a, exponent)`

In [19]:
# Using functions
print("Using torch.add:", torch.add(a, b))

Using torch.add: tensor([5., 7., 9.])


### **5.2 Matrix Operations**
- `torch.mm(A, B)`: Matrix multiplication.
- `torch.matmul(A, B)`: Generalized matrix multiplication.
- `A @ B`: Shorthand for `torch.matmul(A, B)`.
- `torch.dot(a, b)`: Dot product for 1D tensors.

In [20]:
# Creating matrices
A = torch.tensor([[1, 2], [3, 4]])
B = torch.tensor([[5, 6], [7, 8]])

# Matrix multiplication
print("Matrix Multiplication (A @ B):\n", A @ B)

# Dot product
x = torch.tensor([1, 2, 3])
y = torch.tensor([4, 5, 6])
print("Dot Product:", torch.dot(x, y))

Matrix Multiplication (A @ B):
 tensor([[19, 22],
        [43, 50]])
Dot Product: tensor(32)


### **5.3 Reduction Operations**
Reduction operations aggregate values along a dimension.

In [21]:
# Creating a tensor
tensor = torch.tensor([[1, 2, 3], [4, 5, 6]])

# Summation
print("Sum:", torch.sum(tensor))

# Mean and standard deviation
print("Mean:", torch.mean(tensor.float()))
print("Standard Deviation:", torch.std(tensor.float()))

# Min and max
print("Min:", torch.min(tensor))
print("Max:", torch.max(tensor))
print("Argmax (Index of max):", torch.argmax(tensor))
print("Argmin (Index of min):", torch.argmin(tensor))

Sum: tensor(21)
Mean: tensor(3.5000)
Standard Deviation: tensor(1.8708)
Min: tensor(1)
Max: tensor(6)
Argmax (Index of max): tensor(5)
Argmin (Index of min): tensor(0)


### **5.4 Clamping and Rounding**
- `torch.clamp(tensor, min, max)`: Restricts values within a range.
- `torch.round(tensor)`, `torch.floor(tensor)`, `torch.ceil(tensor)`: Rounding operations.

In [22]:
# Creating a tensor with random values
tensor = torch.randn(5) * 10
print("Original Tensor:", tensor)

# Clamping values between -5 and 5
clamped_tensor = torch.clamp(tensor, -5, 5)
print("Clamped Tensor:", clamped_tensor)

# Rounding operations
print("Rounded:", torch.round(tensor))
print("Floored:", torch.floor(tensor))
print("Ceiled:", torch.ceil(tensor))

Original Tensor: tensor([  6.4515,   4.0040,  -8.2213,  -3.3191, -12.6544])
Clamped Tensor: tensor([ 5.0000,  4.0040, -5.0000, -3.3191, -5.0000])
Rounded: tensor([  6.,   4.,  -8.,  -3., -13.])
Floored: tensor([  6.,   4.,  -9.,  -4., -13.])
Ceiled: tensor([  7.,   5.,  -8.,  -3., -12.])


---

### **6. Logical Operations**
- `torch.eq(a, b)`, `torch.ne(a, b)`, `torch.gt(a, b)`, `torch.lt(a, b)`
- `tensor.any()`, `tensor.all()`

---

## **6. Broadcasting and Tensor Operations with Different Shapes**

Broadcasting allows PyTorch to perform operations on tensors of different shapes without explicit expansion.

### **6.1 Broadcasting Basics**
Broadcasting follows these rules:
1. If tensors have different dimensions, the smaller one is expanded by adding dimensions on the left.
2. If sizes differ, the dimension with size `1` is expanded to match the larger one.
3. If dimensions are incompatible, an error occurs.

In [23]:
import torch

# Scalar and vector operation (scalar is broadcasted)
scalar = torch.tensor(3)
vector = torch.tensor([1, 2, 3])
print("Scalar + Vector:", scalar + vector)

# Matrix and vector broadcasting
matrix = torch.tensor([[1, 2, 3], [4, 5, 6]])
print("Matrix + Vector:\n", matrix + vector)

Scalar + Vector: tensor([4, 5, 6])
Matrix + Vector:
 tensor([[2, 4, 6],
        [5, 7, 9]])


### **6.2 Explicit Expansion**
- `torch.unsqueeze(tensor, dim)`: Adds a new dimension.
- `torch.expand(shape)`: Expands a tensor without copying data.

In [24]:
# Creating a 1D tensor
a = torch.tensor([1, 2, 3])

# Unsqueeze to make it a column vector
a_column = a.unsqueeze(1)  # Shape: (3,1)
print("Column Vector:\n", a_column)

# Expanding to a 3x3 matrix
expanded = a_column.expand(3, 3)
print("Expanded Matrix:\n", expanded)

Column Vector:
 tensor([[1],
        [2],
        [3]])
Expanded Matrix:
 tensor([[1, 1, 1],
        [2, 2, 2],
        [3, 3, 3]])


### **6.3 Adding New Dimensions with `None`**
Using `None` in indexing adds a new axis.

In [25]:
# Creating a 1D tensor
tensor = torch.tensor([1, 2, 3])

# Adding an extra dimension
tensor_2d = tensor[None, :]
print("Tensor with New Axis:\n", tensor_2d, "Shape:", tensor_2d.shape)

Tensor with New Axis:
 tensor([[1, 2, 3]]) Shape: torch.Size([1, 3])


### **6.4 Broadcasting in Arithmetic Operations**
When performing operations on mismatched shapes, broadcasting is applied.

In [26]:
# Creating tensors
A = torch.tensor([[1, 2, 3], [4, 5, 6]])
B = torch.tensor([1, 2, 3])  # 1D tensor

# Broadcasting in addition
result = A + B
print("Broadcasted Addition:\n", result)

Broadcasted Addition:
 tensor([[2, 4, 6],
        [5, 7, 9]])


### **6.5 Incompatible Shapes**
If two tensors have incompatible shapes, an error occurs.

In [27]:
# Example of incompatible shapes (will raise an error)
try:
    A = torch.tensor([[1, 2], [3, 4]])
    B = torch.tensor([1, 2, 3])
    print(A + B)  # This will fail
except Exception as e:
    print("Error:", e)

Error: The size of tensor a (2) must match the size of tensor b (3) at non-singleton dimension 1


---

## **7. Tensor Device Management (CPU vs. GPU)**

PyTorch allows you to perform computations on both **CPU** and **GPU** for efficient deep learning workflows.

### **7.1 Checking for GPU Availability**
To check if a GPU is available:

In [28]:
import torch

# Check if CUDA (GPU support) is available
device = "cuda" if torch.cuda.is_available() else "cpu"
print("Device:", device)

Device: cpu


If a GPU is available, it returns `"cuda"`, otherwise, it returns `"cpu"`.

### **7.2 Moving Tensors Between CPU and GPU**
You can move tensors between CPU and GPU using `.to(device)`.

In [29]:
# Creating a tensor on CPU
tensor = torch.tensor([1, 2, 3])
print("Tensor Device Before:", tensor.device)

# Moving tensor to GPU (if available)
tensor_gpu = tensor.to(device)
print("Tensor Device After:", tensor_gpu.device)

Tensor Device Before: cpu
Tensor Device After: cpu


Alternatively, you can use:
- `tensor.cuda()` to move to GPU
- `tensor.cpu()` to move back to CPU

In [30]:
# Moving to GPU
tensor_gpu = tensor.cuda()

# Moving back to CPU
tensor_cpu = tensor_gpu.cpu()

AssertionError: Torch not compiled with CUDA enabled

### **7.3 Creating Tensors Directly on a Specific Device**
You can create tensors directly on the GPU:

In [32]:
# Creating a tensor directly on GPU
tensor_gpu = torch.tensor([10, 20, 30], device="cuda" if torch.cuda.is_available() else "cpu")
print("Tensor on GPU:", tensor_gpu)

Tensor on GPU: tensor([10, 20, 30])


Alternatively, you can specify `device` while using tensor creation functions:

In [33]:
tensor_gpu = torch.zeros(3, device=device)
print("Created Tensor Device:", tensor_gpu.device)

Created Tensor Device: cpu


### **7.4 Performing Operations on GPU**
Operations on GPU tensors are much faster than on CPU.

In [34]:
import time

# Large tensor on CPU
tensor_cpu = torch.randn(10000, 10000)

# Large tensor on GPU (if available)
tensor_gpu = tensor_cpu.to(device)

# Timing CPU operation
start = time.time()
result_cpu = tensor_cpu @ tensor_cpu  # Matrix multiplication
print("CPU Time:", time.time() - start)

# Timing GPU operation (if GPU is available)
if torch.cuda.is_available():
    start = time.time()
    result_gpu = tensor_gpu @ tensor_gpu
    torch.cuda.synchronize()  # Ensure GPU operations are completed
    print("GPU Time:", time.time() - start)

CPU Time: 5.9804582595825195


### **7.5 Ensuring Tensors Are on the Same Device**
Operations between tensors require them to be on the same device.

In [35]:
# Creating CPU and GPU tensors
tensor_cpu = torch.tensor([1, 2, 3])
tensor_gpu = torch.tensor([4, 5, 6], device="cuda" if torch.cuda.is_available() else "cpu")

# Attempting an operation (this will raise an error if devices don't match)
try:
    result = tensor_cpu + tensor_gpu  # This will fail if one is on CPU and the other on GPU
except RuntimeError as e:
    print("Error:", e)

To fix this, move all tensors to the same device before operations.

In [36]:
# Moving CPU tensor to GPU
tensor_cpu = tensor_cpu.to(device)

# Now the operation works
result = tensor_cpu + tensor_gpu
print("Result:", result)

Result: tensor([5, 7, 9])
